# Generated by Django 6.0.7 on 2026-07-19 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seedlings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yolo_status_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
                ('seedling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='seedlings.seedling')),
            ],
        ),
    ]
