# Generated by Django 6.0.7 on 2026-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='diary/illustrations/'),
        ),
    ]
