# Generated by Django 6.0.7 on 2026-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='growth_stage',
            field=models.CharField(blank=True, choices=[('rooting', '발근 중'), ('leafing', '잎 성장 중'), ('branching', '가지 발달'), ('mature', '묘목 완성')], max_length=20, null=True),
        ),
    ]
