# Generated by Django 6.0.7 on 2026-07-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vision/images/')),
                ('result_tag', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('location_info', models.CharField(blank=True, max_length=100, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vision_analyses', to='diary.diary')),
            ],
        ),
    ]
