# Generated by Django 6.0.7 on 2026-07-19 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seedling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('growing', '재배중'), ('completed', '완료')], default='growing', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_or_donate', models.CharField(blank=True, choices=[('pickup', '수령'), ('donate', '기부')], max_length=10, null=True)),
                ('donate_type', models.CharField(blank=True, max_length=50, null=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_seedlings', to=settings.AUTH_USER_MODEL)),
                ('grower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growing_seedlings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
