# Generated by Django 6.0.7 on 2026-08-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedling',
            name='donate_type',
            field=models.CharField(blank=True, choices=[('school_welfare', '초등학교·복지시설 기증'), ('urban_farming_community', '도시농업 공동체·시민단체 연계'), ('in_app_sharing', '앱 내 나눔 분양')], max_length=50, null=True),
        ),
    ]
