# Generated by Django 6.0.7 on 2026-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0002_alter_seedling_donate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedling',
            name='final_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='seedlings/final_illustrations/'),
        ),
        migrations.AddField(
            model_name='seedling',
            name='final_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seedlings/final_photos/'),
        ),
        migrations.AddField(
            model_name='seedling',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
