# Generated by Django 6.0.7 on 2026-07-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seedlings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('gemini_diagnosis', models.TextField(blank=True, null=True)),
                ('seedling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='seedlings.seedling')),
            ],
        ),
    ]
